// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OfficeMate.API.Test.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AddItemToCartFeature : object, Xunit.IClassFixture<AddItemToCartFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Create-AddToCart.feature"
#line hidden
        
        public AddItemToCartFeature(AddItemToCartFeature.FixtureData fixtureData, OfficeMate_API_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Add item to cart", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The users adds a product in the cart and should place a product in the cart")]
        [Xunit.TraitAttribute("FeatureTitle", "Add item to cart")]
        [Xunit.TraitAttribute("Description", "The users adds a product in the cart and should place a product in the cart")]
        public void TheUsersAddsAProductInTheCartAndShouldPlaceAProductInTheCart()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The users adds a product in the cart and should place a product in the cart", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "SKU",
                            "QTY",
                            "CartId"});
                table1.AddRow(new string[] {
                            "OFM5010111",
                            "1",
                            "94051473"});
#line 7
 testRunner.When("the user adds the product to the cart with the details", ((string)(null)), table1, "When ");
#line hidden
#line 10
 testRunner.Then("the user gets a response with code \"200\" message \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "Sku",
                            "OFM5010111"});
                table2.AddRow(new string[] {
                            "Qty",
                            "1"});
                table2.AddRow(new string[] {
                            "Name",
                            "Double A Copier Paper A4 80 gsm. 5 Reams/Pack"});
                table2.AddRow(new string[] {
                            "Price",
                            "518.69"});
                table2.AddRow(new string[] {
                            "Product_Type",
                            "simple"});
#line 11
 testRunner.And("the user gets CartItemDto with following data:", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The user adds invalid product data into the cart and should receive an error mess" +
            "age \"Requested product doesn\'t exist\"")]
        [Xunit.TraitAttribute("FeatureTitle", "Add item to cart")]
        [Xunit.TraitAttribute("Description", "The user adds invalid product data into the cart and should receive an error mess" +
            "age \"Requested product doesn\'t exist\"")]
        public void TheUserAddsInvalidProductDataIntoTheCartAndShouldReceiveAnErrorMessageRequestedProductDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user adds invalid product data into the cart and should receive an error mess" +
                    "age \"Requested product doesn\'t exist\"", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "SKU",
                            "QTY",
                            "CartId"});
                table3.AddRow(new string[] {
                            "0000000000",
                            "1",
                            "94051473"});
#line 23
 testRunner.When("the user adds the product to the cart with the details", ((string)(null)), table3, "When ");
#line hidden
#line 26
 testRunner.Then("the user gets a response with status \"error\" and error message \"Requested product" +
                        " doesn\'t exist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AddItemToCartFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AddItemToCartFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
